# Generated by Django 3.1.5 on 2021-02-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crs_app', '0003_signupmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpModel',
        ),
    ]
